openapi: 3.0.3
info:
  title: Avaliação Técnica - L2
  description: Uma API para consumir e consultar cases da L2 registrados no sistema.
  version: 1.0.0
  contact: {}
servers:
  - url: http://drupal.docker.localhost
paths:
  /cases/export:
    get:
      tags:
        - cases
      summary: exportar casos no formato JSON
      description: Exportar os dados de Cases do Drupal como um JSON.
      operationId: export
      parameters:
        - name: titulo
          description: Filtra os resultados baseado no campo Título dos cases no Drupal
          in: query
          schema:
            type: string
            example: 'Título do Case'
        - name: descricao
          description: Filtra os resultados baseado no campo Descrição dos cases no Drupal
          in: query
          schema:
            type: string
            example: 'Descrição do Case'
      responses:
        '200':
          description: 'Os dados foram exportados corretamente'
        '401':
          description: 'Houve uma falha na autenticação. Verifique o header de Basic Auth'
        '403':
          description: 'Houve uma falha na autorização. As credenciais são inválidas. A credencial default é l2_admin:L2_password'
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
security:
  - basicAuth: []
tags:
  - name: cases
    description: Requests para o endpoint de cases do Drupal.
